define(['questAPI'], function(Quest){
    let API = new Quest();
    let isTouch = API.getGlobal().$isTouch;
	
    /**
	* Page prototype
	*/
    API.addPagesSet('basicPage',{
        noSubmit:false,
        header: 'Demografski podatki',
        decline: true,
        declineText: isTouch ? 'Odkloni' : 'Ne želim odgovoriti', 
        autoFocus:true, 
        progressBar: 'Stran <%= pagesMeta.number %> od 5'
    });

    /**
	* Question prototypes
	*/
    API.addQuestionsSet('basicQ',{
        decline: 'true',
        required: true,
        errorMsg: {
            required: isTouch 
                ? 'Izberite odgovor ali pritisnite \'Odkloni\'' 
                : 'Izberite odgovor ali pritisnite \'Ne želim odgovoriti\''
        },
        autoSubmit:'true',
        numericValues:'true',
        help: '<%= pagesMeta.number < pagesMeta.count %>',
        helpText: 'Nasvet: Če želite odgovoriti hitreje, dvakrat pritisnite na izbrano polje.'
    });

    API.addQuestionsSet('basicSelect',{ inherit:'basicQ', type:'selectOne' });
    API.addQuestionsSet('basicDropdown',{ inherit:'basicQ', type:'dropdown', autoSubmit:false });

    /**
	* Specific demographic questions
	*/
    API.addQuestionsSet('birth_Month', {
	    inherit:'basicSelect',
	    name:'birth_Month',
	    stem:'V katerem mesecu ste rojeni?',
	    style:'multiButtons',
	    minWidth:'7.8%',
	    answers: [
            	{text: 'januar', value: 'januar'},
    		{text: 'februar', value: 'februar'},
		{text: 'marec', value: 'marec'},
		{text: 'april', value: 'april'},
		{text: 'maj', value: 'maj'},
		{text: 'junij', value: 'junij'},
		{text: 'julij', value: 'julij'},
		{text: 'avgust', value: 'avgust'},
		{text: 'september', value: 'september'},
		{text: 'oktober', value: 'oktober'},
		{text: 'november', value: 'november'},
		{text: 'december', value: 'december'}
            ]
    });
	
    API.addQuestionsSet('birth_Year', {
	    inherit:'basicDropdown',
	    name:'birth_Year',
	    stem:'Katerega leta ste rojeni?',
	    answers: [
		{text: '2025', value: '2025'},
	        {text: '2024', value: '2024'},
		{text: '2023', value: '2023'},
	        {text: '2022', value: '2022'},
		{text: '2021', value: '2021'},
	        {text: '2020', value: '2020'},
	        {text: '2019', value: '2019'},
	        {text: '2018', value: '2018'},
	        {text: '2017', value: '2017'},
	        {text: '2016', value: '2016'},
		{text: '2015', value: '2015'},
	        {text: '2014', value: '2014'},
	        {text: '2013', value: '2013'},
	        {text: '2012', value: '2012'},
	        {text: '2011', value: '2011'},
	        {text: '2010', value: '2010'},
	        {text: '2009', value: '2009'},
	        {text: '2008', value: '2008'},
	        {text: '2007', value: '2007'},
	        {text: '2006', value: '2006'},
	        {text: '2005', value: '2005'},
	        {text: '2004', value: '2004'},
	        {text: '2003', value: '2003'},
	        {text: '2002', value: '2002'},
	        {text: '2001', value: '2001'},
	        {text: '2000', value: '2000'},
	        {text: '1999', value: '1999'},
	        {text: '1998', value: '1998'},
	        {text: '1997', value: '1997'},
	        {text: '1996', value: '1996'},
	        {text: '1995', value: '1995'},
	        {text: '1994', value: '1994'},
	        {text: '1993', value: '1993'},
	        {text: '1992', value: '1992'},
	        {text: '1991', value: '1991'},
	        {text: '1990', value: '1990'},
	        {text: '1989', value: '1989'},
	        {text: '1988', value: '1988'},
	        {text: '1987', value: '1987'},
	        {text: '1986', value: '1986'},
	        {text: '1985', value: '1985'},
	        {text: '1984', value: '1984'},
	        {text: '1983', value: '1983'},
	        {text: '1982', value: '1982'},
	        {text: '1981', value: '1981'},
	        {text: '1980', value: '1980'},
	        {text: '1979', value: '1979'},
	        {text: '1978', value: '1978'},
	        {text: '1977', value: '1977'},
	        {text: '1976', value: '1976'},
	        {text: '1975', value: '1975'},
	        {text: '1974', value: '1974'},
	        {text: '1973', value: '1973'},
	        {text: '1972', value: '1972'},
	        {text: '1971', value: '1971'},
	        {text: '1970', value: '1970'},
	        {text: '1969', value: '1969'},
	        {text: '1968', value: '1968'},
	        {text: '1967', value: '1967'},
	        {text: '1966', value: '1966'},
	        {text: '1965', value: '1965'},
	        {text: '1964', value: '1964'},
	        {text: '1963', value: '1963'},
	        {text: '1962', value: '1962'},
	        {text: '1961', value: '1961'},
	        {text: '1960', value: '1960'},
	        {text: '1959', value: '1959'},
	        {text: '1958', value: '1958'},
	        {text: '1957', value: '1957'},
	        {text: '1956', value: '1956'},
	        {text: '1955', value: '1955'},
	        {text: '1954', value: '1954'},
	        {text: '1953', value: '1953'},
	        {text: '1952', value: '1952'},
	        {text: '1951', value: '1951'},
	        {text: '1950', value: '1950'},
	        {text: '1949', value: '1949'},
	        {text: '1948', value: '1948'},
	        {text: '1947', value: '1947'},
	        {text: '1946', value: '1946'},
	        {text: '1945', value: '1945'},
	        {text: '1944', value: '1944'},
	        {text: '1943', value: '1943'},
	        {text: '1942', value: '1942'},
	        {text: '1941', value: '1941'},
	        {text: '1940', value: '1940'},
	        {text: '1939', value: '1939'},
	        {text: '1938', value: '1938'},
	        {text: '1937', value: '1937'},
	        {text: '1936', value: '1936'},
	        {text: '1935', value: '1935'},
	        {text: '1934', value: '1934'},
	        {text: '1933', value: '1933'},
	        {text: '1932', value: '1932'},
	        {text: '1931', value: '1931'},
	        {text: '1930', value: '1930'},
	        {text: '1929', value: '1929'},
	        {text: '1928', value: '1928'},
	        {text: '1927', value: '1927'},
	        {text: '1926', value: '1926'},
	        {text: '1925', value: '1925'},
	        {text: '1924', value: '1924'},
	        {text: '1923', value: '1923'},
	        {text: '1922', value: '1922'},
	        {text: '1921', value: '1921'},
	        {text: '1920', value: '1920'},
	        {text: '1919', value: '1919'},
	        {text: '1918', value: '1918'},
	        {text: '1917', value: '1917'},
	        {text: '1916', value: '1916'},
	        {text: '1915', value: '1915'},
	        {text: '1914', value: '1914'},
	        {text: '1913', value: '1913'},
	        {text: '1912', value: '1912'},
	        {text: '1911', value: '1911'},
	        {text: '1910', value: '1910'},
	        {text: '1909', value: '1909'},
	        {text: '1908', value: '1908'},
	        {text: '1907', value: '1907'},
	        {text: '1906', value: '1906'},
	        {text: '1905', value: '1905'},
	        {text: '1904', value: '1904'},
	        {text: '1903', value: '1903'},
	        {text: '1902', value: '1902'},
	        {text: '1901', value: '1901'},
	        {text: '1900', value: '1900'}
	    ]
        });
	
        API.addQuestionsSet('gender_Identity', {
		inherit:'basicSelect',
		name:'gender_Identity',
		stem:'Kakšna je vaša spolna identiteta?',
		answers: [
			{text: 'Moški', value: 'moski'},
		        {text: 'Ženska', value: 'zenska'},
		        {text: 'Nebinarna oseba', value: 'nebinarna'},
		        {text: 'Drugo', value: 'drugo'}
        	]
	});

	API.addQuestionsSet('gender_Identity_other', {
	    inherit: 'basicText',
	    name: 'gender_Identity_other',
	    stem: 'Prosimo, navedite svojo spolno identiteto:',
	    visibility: function(data) {
	        return data.gender_Identity === 'drugo';
	    }
	});
	
        API.addQuestionsSet('transgender', {
		inherit:'basicSelect',
		name:'transgender',
		stem:'Ali ste transspolna oseba?',
		answers: [
			'Da', 'Ne', 'Ne vem'
        	]
	});
        
	API.addQuestionsSet('citizenship', {
		inherit:'basicDropdown',
		name:'citizenship',
		stem:'Katero je vaše primarno državljanstvo',
		answers: [
	        	{text: 'Afghanistan', value: 'Afghanistan'},
	        	{text: 'Albania', value: 'Albania'},
	        	{text: 'Algeria', value: 'Algeria'},
	        	{text: 'Andorra', value: 'Andorra'},
	        	{text: 'Angola', value: 'Angola'},
	        	{text: 'Antigua and Barbuda', value: 'Antigua and Barbuda'},
	        	{text: 'Argentina', value: 'Argentina'},
	        	{text: 'Armenia', value: 'Armenia'},
	        	{text: 'Australia', value: 'Australia'},
	        	{text: 'Austria', value: 'Austria'},
	        	{text: 'Azerbaijan', value: 'Azerbaijan'},
	        	{text: 'Bahamas', value: 'Bahamas'},
	        	{text: 'Bahrain', value: 'Bahrain'},
	        	{text: 'Bangladesh', value: 'Bangladesh'},
	        	{text: 'Barbados', value: 'Barbados'},
	        	{text: 'Belarus', value: 'Belarus'},
	        	{text: 'Belgium', value: 'Belgium'},
	        	{text: 'Belize', value: 'Belize'},
	        	{text: 'Benin', value: 'Benin'},
	        	{text: 'Bhutan', value: 'Bhutan'},
	        	{text: 'Bolivia', value: 'Bolivia'},
	        	{text: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina'},
	        	{text: 'Botswana', value: 'Botswana'},
	        	{text: 'Brazil', value: 'Brazil'},
	        	{text: 'Brunei', value: 'Brunei'},
	        	{text: 'Bulgaria', value: 'Bulgaria'},
	        	{text: 'Burkina Faso', value: 'Burkina Faso'},
	        	{text: 'Burundi', value: 'Burundi'},
		        {text: 'Cabo Verde', value: 'Cabo Verde'},
		        {text: 'Cambodia', value: 'Cambodia'},
		        {text: 'Cameroon', value: 'Cameroon'},
		        {text: 'Canada', value: 'Canada'},
		        {text: 'Central African Republic', value: 'Central African Republic'},
		        {text: 'Chad', value: 'Chad'},
		        {text: 'Chile', value: 'Chile'},
		        {text: 'China', value: 'China'},
		        {text: 'Colombia', value: 'Colombia'},
		        {text: 'Comoros', value: 'Comoros'},
		        {text: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)'},
		        {text: 'Congo (Congo-Kinshasa)', value: 'Congo (Congo-Kinshasa)'},
		        {text: 'Costa Rica', value: 'Costa Rica'},
		        {text: 'Croatia', value: 'Croatia'},
		        {text: 'Cuba', value: 'Cuba'},
		        {text: 'Cyprus', value: 'Cyprus'},
		        {text: 'Czech Republic', value: 'Czech Republic'},
		        {text: 'Denmark', value: 'Denmark'},
		        {text: 'Djibouti', value: 'Djibouti'},
		        {text: 'Dominica', value: 'Dominica'},
		        {text: 'Dominican Republic', value: 'Dominican Republic'},
		        {text: 'Ecuador', value: 'Ecuador'},
		        {text: 'Egypt', value: 'Egypt'},
		        {text: 'El Salvador', value: 'El Salvador'},
		        {text: 'Equatorial Guinea', value: 'Equatorial Guinea'},
		        {text: 'Eritrea', value: 'Eritrea'},
		        {text: 'Estonia', value: 'Estonia'},
		        {text: 'Eswatini', value: 'Eswatini'},
		        {text: 'Ethiopia', value: 'Ethiopia'},
		        {text: 'Fiji', value: 'Fiji'},
		        {text: 'Finland', value: 'Finland'},
		        {text: 'France', value: 'France'},
		        {text: 'Gabon', value: 'Gabon'},
		        {text: 'Gambia', value: 'Gambia'},
		        {text: 'Georgia', value: 'Georgia'},
		        {text: 'Germany', value: 'Germany'},
		        {text: 'Ghana', value: 'Ghana'},
		        {text: 'Greece', value: 'Greece'},
		        {text: 'Grenada', value: 'Grenada'},
		        {text: 'Guatemala', value: 'Guatemala'},
		        {text: 'Guinea', value: 'Guinea'},
		        {text: 'Guinea-Bissau', value: 'Guinea-Bissau'},
		        {text: 'Guyana', value: 'Guyana'},
		        {text: 'Haiti', value: 'Haiti'},
		        {text: 'Honduras', value: 'Honduras'},
		        {text: 'Hungary', value: 'Hungary'},
		        {text: 'Iceland', value: 'Iceland'},
		        {text: 'India', value: 'India'},
		        {text: 'Indonesia', value: 'Indonesia'},
		        {text: 'Iran', value: 'Iran'},
		        {text: 'Iraq', value: 'Iraq'},
		        {text: 'Ireland', value: 'Ireland'},
		        {text: 'Israel', value: 'Israel'},
		        {text: 'Italy', value: 'Italy'},
		        {text: 'Jamaica', value: 'Jamaica'},
		        {text: 'Japan', value: 'Japan'},
		        {text: 'Jordan', value: 'Jordan'},
		        {text: 'Kazakhstan', value: 'Kazakhstan'},
		        {text: 'Kenya', value: 'Kenya'},
		        {text: 'Kiribati', value: 'Kiribati'},
		        {text: 'Korea (North)', value: 'Korea (North)'},
		        {text: 'Korea (South)', value: 'Korea (South)'},
		        {text: 'Kuwait', value: 'Kuwait'},
		        {text: 'Kyrgyzstan', value: 'Kyrgyzstan'},
		        {text: 'Laos', value: 'Laos'},
		        {text: 'Latvia', value: 'Latvia'},
		        {text: 'Lebanon', value: 'Lebanon'},
		        {text: 'Lesotho', value: 'Lesotho'},
		        {text: 'Liberia', value: 'Liberia'},
		        {text: 'Libya', value: 'Libya'},
		        {text: 'Liechtenstein', value: 'Liechtenstein'},
		        {text: 'Lithuania', value: 'Lithuania'},
		        {text: 'Luxembourg', value: 'Luxembourg'},
		        {text: 'Madagascar', value: 'Madagascar'},
		        {text: 'Malawi', value: 'Malawi'},
		        {text: 'Malaysia', value: 'Malaysia'},
		        {text: 'Maldives', value: 'Maldives'},
		        {text: 'Mali', value: 'Mali'},
		        {text: 'Malta', value: 'Malta'},
		        {text: 'Marshall Islands', value: 'Marshall Islands'},
		        {text: 'Mauritania', value: 'Mauritania'},
		        {text: 'Mauritius', value: 'Mauritius'},
		        {text: 'Mexico', value: 'Mexico'},
		        {text: 'Micronesia', value: 'Micronesia'},
		        {text: 'Moldova', value: 'Moldova'},
		        {text: 'Monaco', value: 'Monaco'},
		        {text: 'Mongolia', value: 'Mongolia'},
		        {text: 'Montenegro', value: 'Montenegro'},
		        {text: 'Morocco', value: 'Morocco'},
		        {text: 'Mozambique', value: 'Mozambique'},
		        {text: 'Myanmar', value: 'Myanmar'},
		        {text: 'Namibia', value: 'Namibia'},
		        {text: 'Nauru', value: 'Nauru'},
		        {text: 'Nepal', value: 'Nepal'},
		        {text: 'Netherlands', value: 'Netherlands'},
		        {text: 'New Zealand', value: 'New Zealand'},
		        {text: 'Nicaragua', value: 'Nicaragua'},
		        {text: 'Niger', value: 'Niger'},
		        {text: 'Nigeria', value: 'Nigeria'},
		        {text: 'North Macedonia', value: 'North Macedonia'},
		        {text: 'Norway', value: 'Norway'},
		        {text: 'Oman', value: 'Oman'},
		        {text: 'Pakistan', value: 'Pakistan'},
		        {text: 'Palau', value: 'Palau'},
		        {text: 'Panama', value: 'Panama'},
		        {text: 'Papua New Guinea', value: 'Papua New Guinea'},
		        {text: 'Paraguay', value: 'Paraguay'},
		        {text: 'Peru', value: 'Peru'},
		        {text: 'Philippines', value: 'Philippines'},
		        {text: 'Poland', value: 'Poland'},
		        {text: 'Portugal', value: 'Portugal'},
		        {text: 'Qatar', value: 'Qatar'},
		        {text: 'Romania', value: 'Romania'},
		        {text: 'Russia', value: 'Russia'},
		        {text: 'Rwanda', value: 'Rwanda'},
		        {text: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis'},
		        {text: 'Saint Lucia', value: 'Saint Lucia'},
		        {text: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines'},
		        {text: 'Samoa', value: 'Samoa'},
		        {text: 'San Marino', value: 'San Marino'},
		        {text: 'Sao Tome and Principe', value: 'Sao Tome and Principe'},
		        {text: 'Saudi Arabia', value: 'Saudi Arabia'},
		        {text: 'Senegal', value: 'Senegal'},
		        {text: 'Serbia', value: 'Serbia'},
		        {text: 'Seychelles', value: 'Seychelles'},
		        {text: 'Sierra Leone', value: 'Sierra Leone'},
		        {text: 'Singapore', value: 'Singapore'},
		        {text: 'Slovakia', value: 'Slovakia'},
		        {text: 'Slovenia', value: 'Slovenia'},
		        {text: 'Solomon Islands', value: 'Solomon Islands'},
		        {text: 'Somalia', value: 'Somalia'},
		        {text: 'South Africa', value: 'South Africa'},
		        {text: 'South Sudan', value: 'South Sudan'},
		        {text: 'Spain', value: 'Spain'},
		        {text: 'Sri Lanka', value: 'Sri Lanka'},
		        {text: 'Sudan', value: 'Sudan'},
		        {text: 'Suriname', value: 'Suriname'},
		        {text: 'Sweden', value: 'Sweden'},
		        {text: 'Switzerland', value: 'Switzerland'},
		        {text: 'Syria', value: 'Syria'},
		        {text: 'Taiwan', value: 'Taiwan'},
		        {text: 'Tajikistan', value: 'Tajikistan'},
		        {text: 'Tanzania', value: 'Tanzania'},
		        {text: 'Thailand', value: 'Thailand'},
		        {text: 'Timor-Leste', value: 'Timor-Leste'},
		        {text: 'Togo', value: 'Togo'},
		        {text: 'Tonga', value: 'Tonga'},
		        {text: 'Trinidad and Tobago', value: 'Trinidad and Tobago'},
		        {text: 'Tunisia', value: 'Tunisia'},
		        {text: 'Turkey', value: 'Turkey'},
		        {text: 'Turkmenistan', value: 'Turkmenistan'},
		        {text: 'Tuvalu', value: 'Tuvalu'},
		        {text: 'Uganda', value: 'Uganda'},
		        {text: 'Ukraine', value: 'Ukraine'},
		        {text: 'United Arab Emirates', value: 'United Arab Emirates'},
		        {text: 'United Kingdom', value: 'United Kingdom'},
		        {text: 'United States', value: 'United States'},
		        {text: 'Uruguay', value: 'Uruguay'},
		        {text: 'Uzbekistan', value: 'Uzbekistan'},
		        {text: 'Vanuatu', value: 'Vanuatu'},
		        {text: 'Vatican City', value: 'Vatican City'},
		        {text: 'Venezuela', value: 'Venezuela'},
		        {text: 'Vietnam', value: 'Vietnam'},
		        {text: 'Yemen', value: 'Yemen'},
		        {text: 'Zambia', value: 'Zambia'},
		        {text: 'Zimbabwe', value: 'Zimbabwe'}
    		]
	});
	
        API.addQuestionsSet('current_Country', {
		inherit:'basicDropdown',
		name:'current_Country',
		stem:'V kateri državi trenutno bivate?',
		answers: [
		        {text: 'Afghanistan', value: 'Afghanistan'},
		        {text: 'Albania', value: 'Albania'},
		        {text: 'Algeria', value: 'Algeria'},
		        {text: 'Andorra', value: 'Andorra'},
		        {text: 'Angola', value: 'Angola'},
		        {text: 'Antigua and Barbuda', value: 'Antigua and Barbuda'},
		        {text: 'Argentina', value: 'Argentina'},
		        {text: 'Armenia', value: 'Armenia'},
		        {text: 'Australia', value: 'Australia'},
		        {text: 'Austria', value: 'Austria'},
		        {text: 'Azerbaijan', value: 'Azerbaijan'},
		        {text: 'Bahamas', value: 'Bahamas'},
		        {text: 'Bahrain', value: 'Bahrain'},
		        {text: 'Bangladesh', value: 'Bangladesh'},
		        {text: 'Barbados', value: 'Barbados'},
		        {text: 'Belarus', value: 'Belarus'},
		        {text: 'Belgium', value: 'Belgium'},
		        {text: 'Belize', value: 'Belize'},
		        {text: 'Benin', value: 'Benin'},
		        {text: 'Bhutan', value: 'Bhutan'},
		        {text: 'Bolivia', value: 'Bolivia'},
		        {text: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina'},
		        {text: 'Botswana', value: 'Botswana'},
		        {text: 'Brazil', value: 'Brazil'},
		        {text: 'Brunei', value: 'Brunei'},
		        {text: 'Bulgaria', value: 'Bulgaria'},
		        {text: 'Burkina Faso', value: 'Burkina Faso'},
		        {text: 'Burundi', value: 'Burundi'},
		        {text: 'Cabo Verde', value: 'Cabo Verde'},
		        {text: 'Cambodia', value: 'Cambodia'},
		        {text: 'Cameroon', value: 'Cameroon'},
		        {text: 'Canada', value: 'Canada'},
		        {text: 'Central African Republic', value: 'Central African Republic'},
		        {text: 'Chad', value: 'Chad'},
		        {text: 'Chile', value: 'Chile'},
		        {text: 'China', value: 'China'},
		        {text: 'Colombia', value: 'Colombia'},
		        {text: 'Comoros', value: 'Comoros'},
		        {text: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)'},
		        {text: 'Congo (Congo-Kinshasa)', value: 'Congo (Congo-Kinshasa)'},
		        {text: 'Costa Rica', value: 'Costa Rica'},
		        {text: 'Croatia', value: 'Croatia'},
		        {text: 'Cuba', value: 'Cuba'},
		        {text: 'Cyprus', value: 'Cyprus'},
		        {text: 'Czech Republic', value: 'Czech Republic'},
		        {text: 'Denmark', value: 'Denmark'},
		        {text: 'Djibouti', value: 'Djibouti'},
		        {text: 'Dominica', value: 'Dominica'},
		        {text: 'Dominican Republic', value: 'Dominican Republic'},
		        {text: 'Ecuador', value: 'Ecuador'},
		        {text: 'Egypt', value: 'Egypt'},
		        {text: 'El Salvador', value: 'El Salvador'},
		        {text: 'Equatorial Guinea', value: 'Equatorial Guinea'},
		        {text: 'Eritrea', value: 'Eritrea'},
		        {text: 'Estonia', value: 'Estonia'},
		        {text: 'Eswatini', value: 'Eswatini'},
		        {text: 'Ethiopia', value: 'Ethiopia'},
		        {text: 'Fiji', value: 'Fiji'},
		        {text: 'Finland', value: 'Finland'},
		        {text: 'France', value: 'France'},
		        {text: 'Gabon', value: 'Gabon'},
		        {text: 'Gambia', value: 'Gambia'},
		        {text: 'Georgia', value: 'Georgia'},
		        {text: 'Germany', value: 'Germany'},
		        {text: 'Ghana', value: 'Ghana'},
		        {text: 'Greece', value: 'Greece'},
		        {text: 'Grenada', value: 'Grenada'},
		        {text: 'Guatemala', value: 'Guatemala'},
		        {text: 'Guinea', value: 'Guinea'},
		        {text: 'Guinea-Bissau', value: 'Guinea-Bissau'},
		        {text: 'Guyana', value: 'Guyana'},
		        {text: 'Haiti', value: 'Haiti'},
		        {text: 'Honduras', value: 'Honduras'},
		        {text: 'Hungary', value: 'Hungary'},
		        {text: 'Iceland', value: 'Iceland'},
		        {text: 'India', value: 'India'},
		        {text: 'Indonesia', value: 'Indonesia'},
		        {text: 'Iran', value: 'Iran'},
		        {text: 'Iraq', value: 'Iraq'},
		        {text: 'Ireland', value: 'Ireland'},
		        {text: 'Israel', value: 'Israel'},
		        {text: 'Italy', value: 'Italy'},
		        {text: 'Jamaica', value: 'Jamaica'},
		        {text: 'Japan', value: 'Japan'},
		        {text: 'Jordan', value: 'Jordan'},
		        {text: 'Kazakhstan', value: 'Kazakhstan'},
		        {text: 'Kenya', value: 'Kenya'},
		        {text: 'Kiribati', value: 'Kiribati'},
		        {text: 'Korea (North)', value: 'Korea (North)'},
		        {text: 'Korea (South)', value: 'Korea (South)'},
		        {text: 'Kuwait', value: 'Kuwait'},
		        {text: 'Kyrgyzstan', value: 'Kyrgyzstan'},
		        {text: 'Laos', value: 'Laos'},
		        {text: 'Latvia', value: 'Latvia'},
		        {text: 'Lebanon', value: 'Lebanon'},
		        {text: 'Lesotho', value: 'Lesotho'},
		        {text: 'Liberia', value: 'Liberia'},
		        {text: 'Libya', value: 'Libya'},
		        {text: 'Liechtenstein', value: 'Liechtenstein'},
		        {text: 'Lithuania', value: 'Lithuania'},
		        {text: 'Luxembourg', value: 'Luxembourg'},
		        {text: 'Madagascar', value: 'Madagascar'},
		        {text: 'Malawi', value: 'Malawi'},
		        {text: 'Malaysia', value: 'Malaysia'},
		        {text: 'Maldives', value: 'Maldives'},
		        {text: 'Mali', value: 'Mali'},
		        {text: 'Malta', value: 'Malta'},
		        {text: 'Marshall Islands', value: 'Marshall Islands'},
		        {text: 'Mauritania', value: 'Mauritania'},
		        {text: 'Mauritius', value: 'Mauritius'},
		        {text: 'Mexico', value: 'Mexico'},
		        {text: 'Micronesia', value: 'Micronesia'},
		        {text: 'Moldova', value: 'Moldova'},
		        {text: 'Monaco', value: 'Monaco'},
		        {text: 'Mongolia', value: 'Mongolia'},
		        {text: 'Montenegro', value: 'Montenegro'},
		        {text: 'Morocco', value: 'Morocco'},
		        {text: 'Mozambique', value: 'Mozambique'},
		        {text: 'Myanmar', value: 'Myanmar'},
		        {text: 'Namibia', value: 'Namibia'},
		        {text: 'Nauru', value: 'Nauru'},
		        {text: 'Nepal', value: 'Nepal'},
		        {text: 'Netherlands', value: 'Netherlands'},
		        {text: 'New Zealand', value: 'New Zealand'},
		        {text: 'Nicaragua', value: 'Nicaragua'},
		        {text: 'Niger', value: 'Niger'},
		        {text: 'Nigeria', value: 'Nigeria'},
		        {text: 'North Macedonia', value: 'North Macedonia'},
		        {text: 'Norway', value: 'Norway'},
		        {text: 'Oman', value: 'Oman'},
		        {text: 'Pakistan', value: 'Pakistan'},
		        {text: 'Palau', value: 'Palau'},
		        {text: 'Panama', value: 'Panama'},
		        {text: 'Papua New Guinea', value: 'Papua New Guinea'},
		        {text: 'Paraguay', value: 'Paraguay'},
		        {text: 'Peru', value: 'Peru'},
		        {text: 'Philippines', value: 'Philippines'},
		        {text: 'Poland', value: 'Poland'},
		        {text: 'Portugal', value: 'Portugal'},
		        {text: 'Qatar', value: 'Qatar'},
		        {text: 'Romania', value: 'Romania'},
		        {text: 'Russia', value: 'Russia'},
		        {text: 'Rwanda', value: 'Rwanda'},
		        {text: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis'},
		        {text: 'Saint Lucia', value: 'Saint Lucia'},
		        {text: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines'},
		        {text: 'Samoa', value: 'Samoa'},
		        {text: 'San Marino', value: 'San Marino'},
		        {text: 'Sao Tome and Principe', value: 'Sao Tome and Principe'},
		        {text: 'Saudi Arabia', value: 'Saudi Arabia'},
		        {text: 'Senegal', value: 'Senegal'},
		        {text: 'Serbia', value: 'Serbia'},
		        {text: 'Seychelles', value: 'Seychelles'},
		        {text: 'Sierra Leone', value: 'Sierra Leone'},
		        {text: 'Singapore', value: 'Singapore'},
		        {text: 'Slovakia', value: 'Slovakia'},
		        {text: 'Slovenia', value: 'Slovenia'},
		        {text: 'Solomon Islands', value: 'Solomon Islands'},
		        {text: 'Somalia', value: 'Somalia'},
		        {text: 'South Africa', value: 'South Africa'},
		        {text: 'South Sudan', value: 'South Sudan'},
		        {text: 'Spain', value: 'Spain'},
		        {text: 'Sri Lanka', value: 'Sri Lanka'},
		        {text: 'Sudan', value: 'Sudan'},
		        {text: 'Suriname', value: 'Suriname'},
		        {text: 'Sweden', value: 'Sweden'},
		        {text: 'Switzerland', value: 'Switzerland'},
		        {text: 'Syria', value: 'Syria'},
		        {text: 'Taiwan', value: 'Taiwan'},
		        {text: 'Tajikistan', value: 'Tajikistan'},
		        {text: 'Tanzania', value: 'Tanzania'},
		        {text: 'Thailand', value: 'Thailand'},
		        {text: 'Timor-Leste', value: 'Timor-Leste'},
		        {text: 'Togo', value: 'Togo'},
		        {text: 'Tonga', value: 'Tonga'},
		        {text: 'Trinidad and Tobago', value: 'Trinidad and Tobago'},
		        {text: 'Tunisia', value: 'Tunisia'},
		        {text: 'Turkey', value: 'Turkey'},
		        {text: 'Turkmenistan', value: 'Turkmenistan'},
		        {text: 'Tuvalu', value: 'Tuvalu'},
		        {text: 'Uganda', value: 'Uganda'},
		        {text: 'Ukraine', value: 'Ukraine'},
		        {text: 'United Arab Emirates', value: 'United Arab Emirates'},
		        {text: 'United Kingdom', value: 'United Kingdom'},
		        {text: 'United States', value: 'United States'},
		        {text: 'Uruguay', value: 'Uruguay'},
		        {text: 'Uzbekistan', value: 'Uzbekistan'},
		        {text: 'Vanuatu', value: 'Vanuatu'},
		        {text: 'Vatican City', value: 'Vatican City'},
		        {text: 'Venezuela', value: 'Venezuela'},
		        {text: 'Vietnam', value: 'Vietnam'},
		        {text: 'Yemen', value: 'Yemen'},
		        {text: 'Zambia', value: 'Zambia'},
		        {text: 'Zimbabwe', value: 'Zimbabwe'}
	    	]
	});
	
        API.addQuestionsSet('education', {
		inherit:'basicDropdown',
		name:'education',
		stem:'Katera je vaša najvišje pridobljena stopnja izobrazbe?',
		answers: [
			{text: 'osnovna šola', value: '1'},
			{text: 'srednja šola', value: '2'},
			{text: 'višja strokovna šola', value: '3'},
			{text: 'univerzitetna diploma 1. stopnje', value: '4'},
			{text: 'univerzitetna diploma 2. stopnje', value: '5'},
			{text: 'druga visokošolska izobrazba', value: '6'},
			{text: 'doktorat', value: '7'}
        	]
	});

    /**
	* Sequence: present demographic questions
	*/
    API.addSequence([
    {
        inherit: 'basicPage',
	decline: false,
        questions: [
            {inherit: 'birth_Month'}
        ]
    },
    {
        inherit: 'basicPage',
	decline: false,
        questions: [
            {inherit: 'birth_Year'}
        ]
    },
    {
        inherit: 'basicPage',
        questions: [
            {inherit:'gender_Identity'},
	    {inherit: 'gender_Identity_other'},
	    {inherit: 'transgender'}
        ]
    },
    {
        inherit: 'basicPage',
        questions: [
            {inherit: 'citizenship'},
	    {inherit: 'current_Country'}
        ]
    },
    {
        inherit: 'basicPage',
        questions: [
            {inherit: 'education'}
        ]
    }
]);

    return API.script;
});
